#!/bin/bash

function start_chat() {

    OSX=0          # If you are on OS X set it to smth.
    TEMPDIR="/tmp" # Directory to store FIFO tempfile.

    NAME=$(echo "$*" | grep -o '[^ ]*@[^ ]*' | cut -d@ -f1)   # Getting user name.
    SERVER=$(echo "$*" | grep -o '[^ ]*@[^ ]*' | cut -d@ -f2) # Getting server name.

    # If user hadn't specified his name.
    if [ -z "${NAME}" ]; then
        NAME=$USER
    fi

    mkfifo $TEMPDIR/$NAME                                 # Creating a FIFO tempfile.
    trap "rm $TEMPDIR/$NAME ; exit" SIGTERM SIGHUP SIGINT # Clearing the FIFO on kill.

    # Reading FIFO file in another thread.
    (cat -u -e $TEMPDIR/$NAME | while read line; do

        # Notifying if meeting out name in others msgs.
        if echo "$line" | grep -q '\^G\^M\^M'; then

            SENDER_NAME=$(get_name "$line")
            SENDER_TEXT=$(get_text "$line")

            # Check if we are on OS X.
            if ! [ $OSX -eq 0 ]; then
                osascript -e 'display notification "'"${SENDER_TEXT//\"/\\\"}"'" with title "Mentioned by "'"${SENDER_NAME//\"/\\\"}"'"'
            else
                notify-send "Mentioned by $SENDER_NAME" "$SENDER_TEXT"
            fi

            echo $line >> $TEMPDIR/log

        fi
    done & ) > /dev/null 2>&1 # Removing backgroung process info from output.

    ssh -t $* | tee $TEMPDIR/$NAME # Connecting to server and translating to FIFO.

    rm $TEMPDIR/$NAME # Kill the FIFO when done (should kill other threads).
    # killall cat # Stop reading file.
}

function get_name() {
    SENDER_NAME=sample_name
    echo $SENDER_NAME
}

function get_text() {
    SENDER_TEXT=$1
    echo $SENDER_TEXT
}

start_chat $*
